version: '3.8'
services:
  mongo_user:
    image: mongo:6.0.6
    restart: always
    hostname: mongo
    ports:
      - "27072:27017"

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
